### ISSUE TITLE
SUCX 3.0 citation has wrong url

### ISSUE THREAD

**Issue by AddedK** [kb-labb/kb-labb.github.io#1]
At the very end of the blog post "SUCX 3.0 - NER" citation information is provided.
However, the URL is "https://kblabb.github.io/posts/2022-02-07-sucx3_ner/", which gives a 404 error.
The correct URL of the blog post is "https://kb-labb.github.io/posts/2022-02-07-sucx3_ner/".
Note the "-".

**Comment by AddedK** [comment]
Investigating further, it seems that multiple blog posts have the same issue, namely that the URL is missing a hyphen.
Is this perhaps a deliberate convention with regards to citation that I am not aware of?

**Comment by RobinQrtz** [comment]
Thank you for pointing that out!

This was (probably @Lauler?!) not intentional.
I believe we will have to recompile the posts or hack the html-files, but I leave that to an expert.

**Comment by RobinQrtz** [comment]
I don't want to promise anything, but all the URLs in the citation boxes should now be fixed.

Thank you.
